-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 22:31:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gatadourada
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gatadourada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gatadourada` DEFAULT CHARACTER SET utf8mb4 ;
USE `gatadourada` ;

-- -----------------------------------------------------
-- Table `gatadourada`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gatadourada`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NULL,
  `idade` INT NULL,
  `dataAlt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `genero` CHAR(1) NOT NULL,
  `numero` INT(11) NOT NULL,
  `email` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `fototipo` INT NULL,
  `jaRealizou` TINYINT NULL,
  `pele` VARCHAR(45) NULL,
  `respiratorio` TINYINT NULL,
  `respiratorioDesc` VARCHAR(45) NULL,
  `hipertensao` TINYINT NULL,
  `degenerativa` TINYINT NULL,
  `alergia` TINYINT NULL,
  `alergiaDesc` VARCHAR(45) NULL,
  `ferimentoTatuagem` TINYINT NULL,
  `ferimentoTatuagemDesc` VARCHAR(45) NULL,
  `hematoma` TINYINT NULL,
  `hematomaDesc` VARCHAR(45) NULL,
  `medicacao` TINYINT NULL,
  `medicacaoDesc` VARCHAR(45) NULL,
  `transpiracao` TINYINT NULL,
  `transpiraçãoDesc` VARCHAR(45) NULL,
  `depilacao` TINYINT NULL,
  `depilacaoDesc` VARCHAR(45) NULL,
  `vitiligo` TINYINT NULL,
  `vitiligoDesc` VARCHAR(45) NULL,
  `psoriase` TINYINT NULL,
  `autorizacao` TINYINT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gatadourada`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gatadourada`.`servicos` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `nomeServico` VARCHAR(45) NULL,
  `valorServico` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gatadourada`.`adicionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gatadourada`.`adicionais` (
  `idAdicional` INT NOT NULL AUTO_INCREMENT,
  `nomeAdicional` INT NULL,
  `valorAdicional` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idAdicional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gatadourada`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gatadourada`.`agenda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(300) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `url` VARCHAR(300) NOT NULL,
  `allDay` VARCHAR(11) NOT NULL,
  `status` INT(11) NOT NULL,
  `color` VARCHAR(300) NOT NULL,
  `procedimento` VARCHAR(300) NOT NULL,
  `valor` FLOAT NOT NULL,
  `forma_pagamento` VARCHAR(200) NOT NULL,
  `tipo_evento` VARCHAR(200) NOT NULL,
  `clientes_id` INT(11) NOT NULL,
  `servicos_idServico` INT NOT NULL,
  `adicionais_idAdicionais` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agenda_clientes_idx` (`clientes_id`),
  INDEX `fk_agenda_servicos1_idx` (`servicos_idServico`),
  INDEX `fk_agenda_adicionais1_idx` (`adicionais_idAdicionais`),
  CONSTRAINT `fk_agenda_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `gatadourada`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_servicos1`
    FOREIGN KEY (`servicos_idServico`)
    REFERENCES `gatadourada`.`servicos` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_adicionais1`
    FOREIGN KEY (`adicionais_idAdicionais`)
    REFERENCES `gatadourada`.`adicionais` (`idAdicional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gatadourada`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gatadourada`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
